import React,{useEffect,useMemo,useState} from "react";
import {Code2,FileCode2,FileJson,FileText,Folder,FolderOpen,GitBranch,Lock,Plus,RefreshCw,Save,Search,ShieldCheck,Trash2,UserPlus,X,ChevronDown,ChevronRight} from "lucide-react";
type CodeFile={path:string;mime:string;is_binary:number;size:number;github_sha?:string|null;updated_by?:string;updated_at:number};
type Member={email:string;role:string;active:number;updated_at:number};
const ext=(p:string)=>p.split(".").pop()?.toLowerCase()||"";
const iconFor=(p:string)=>{const e=ext(p);if(["json","jsonc"].includes(e))return <FileJson size={15}/>;if(["ts","tsx","js","jsx","css","html","sql"].includes(e))return <FileCode2 size={15}/>;return <FileText size={15}/>};
function buildTree(paths:string[]){const root:any={children:{}};for(const path of paths){let n=root;const parts=path.split("/");parts.forEach((part,i)=>{n.children[part]??={name:part,children:{},file:null};n=n.children[part];if(i===parts.length-1)n.file=path})}return root}
function Tree({node,prefix,onOpen,active}:{node:any;prefix:string;onOpen:(p:string)=>void;active:string}){const [open,setOpen]=useState(true);const items=Object.values(node.children||{}) as any[];items.sort((x,y)=>Number(Boolean(y.file))-Number(Boolean(x.file))||x.name.localeCompare(y.name));return <>{items.map(c=>{const full=prefix?prefix+"/"+c.name:c.name;return c.file?<button className={"cs-tree-file "+(active===c.file?"active":"")} key={full} onClick={()=>onOpen(c.file)}>{iconFor(c.file)}<span>{c.name}</span></button>:<div key={full}><button className="cs-tree-folder" onClick={()=>setOpen(v=>!v)}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<Folder size={15}/><span>{c.name}</span></button>{open&&<div className="cs-tree-indent"><Tree node={c} prefix={full} onOpen={onOpen} active={active}/></div>}</div>})}</>}
export default function CodeStudioPage(){
 const [files,setFiles]=useState<CodeFile[]>([]),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(""),[content,setContent]=useState(""),[saved,setSaved]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[newPath,setNewPath]=useState(""),[memberEmail,setMemberEmail]=useState(""),[memberOpen,setMemberOpen]=useState(false),[owner,setOwner]=useState(false),[role,setRole]=useState("");
 const load=async()=>{setError("");try{const r=await fetch("/api/codebase",{credentials:"same-origin",cache:"no-store"}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d?.error||"Could not open Code Studio."),{code:d?.code});setFiles(d.files||[]);setMembers(d.members||[]);setOwner(Boolean(d.owner));setRole(d.role||"")}catch(e:any){setError(e?.message||"Could not open Code Studio.");if(e?.code==="GOOGLE_REQUIRED")setTimeout(()=>location.href="/api/auth/google",700)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(path:string)=>{setSelected(path);try{const r=await fetch("/api/codebase?path="+encodeURIComponent(path),{credentials:"same-origin"}),d=await r.json();if(!r.ok)throw new Error(d?.error||"Could not load file.");const text=d.file?.is_binary?"[Binary file — stored in the virtual codebase but not editable as text.]\n\nSize: "+d.file.size+" bytes":String(d.file?.content||"");setContent(text);setSaved(d.file?.is_binary?"":String(d.file?.content||""))}catch(e:any){setError(e?.message||"Could not load file.")}};
 const save=async()=>{if(!selected||saving)return;setSaving(true);try{const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({path:selected,content,mime:files.find(f=>f.path===selected)?.mime})}),d=await r.json();if(!r.ok)throw new Error(d?.error||"Save failed.");setSaved(content);setFiles(p=>p.map(f=>f.path===selected?{...f,updated_by:"you",updated_at:Date.now()/1000}:f))}catch(e:any){setError(e?.message||"Save failed.")}finally{setSaving(false)}};
 const create=async()=>{const path=newPath.trim();if(!path)return;const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({path,content:"",mime:"text/plain"})}),d=await r.json();if(!r.ok){setError(d?.error||"Could not create file.");return}setNewPath("");setFiles(p=>p.some(f=>f.path===path)?p:[...p,{path,mime:"text/plain",is_binary:0,size:0,updated_at:Date.now()/1000}]);setSelected(path);setContent("");setSaved("")};
 const remove=async()=>{if(!selected||!confirm("Delete this file from the virtual codebase?"))return;const r=await fetch("/api/codebase?path="+encodeURIComponent(selected),{method:"DELETE",credentials:"same-origin"}),d=await r.json();if(!r.ok){setError(d?.error||"Delete failed.");return}setFiles(p=>p.filter(f=>f.path!==selected));setSelected("");setContent("");setSaved("")};
 const sync=async()=>{if(!owner)return;setSyncing(true);try{const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"sync"})}),d=await r.json();if(!r.ok)throw new Error(d?.error||"Sync failed.");await load()}catch(e:any){setError(e?.message||"GitHub sync failed.")}finally{setSyncing(false)}};
 const addMember=async()=>{if(!memberEmail.trim())return;const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"member",email:memberEmail})}),d=await r.json();if(!r.ok){setError(d?.error||"Could not add member.");return}setMemberEmail("");setMemberOpen(false);await load()};
 const filtered=useMemo(()=>files.filter(f=>!search||f.path.toLowerCase().includes(search.toLowerCase())),[files,search]),root=buildTree(filtered.map(f=>f.path)),dirty=Boolean(selected)&&content!==saved;
 if(loading)return <div className="cs-loading"><Code2 size={26}/><b>Opening Code Studio…</b><span>Loading the virtual codebase.</span></div>;
 return <div className="code-studio">
  <header className="cs-top"><div className="cs-brand"><div className="cs-logo"><Code2 size={18}/></div><div><b>Code Studio</b><span>Cookie codebase</span></div></div><div className="cs-status"><GitBranch size={15}/>main<span>•</span>{files.length} files<span>•</span><ShieldCheck size={14}/>{role}</div><div className="cs-actions"><button onClick={sync} disabled={!owner||syncing}><RefreshCw size={15}/>{syncing?"Syncing…":"Sync"}</button><button onClick={()=>setMemberOpen(true)}><UserPlus size={15}/>Members</button></div></header>
  {error&&<div className="cs-error">{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}
  <div className="cs-main"><aside className="cs-sidebar"><div className="cs-sidebar-head"><b>EXPLORER</b><button onClick={()=>setNewPath("src/new-file.ts")}><Plus size={15}/></button></div><div className="cs-search"><Search size={14}/><input placeholder="Search files" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="cs-root"><FolderOpen size={15}/><b>COOKIE</b></div><div className="cs-tree"><Tree node={root} prefix="" onOpen={open} active={selected}/></div><div className="cs-side-foot"><Lock size={13}/>Virtual workspace · changes stay in Cookie until committed.</div></aside>
  <section className="cs-editor"><div className="cs-tabs">{selected?<div className="cs-tab active">{iconFor(selected)}<span>{selected.split("/").pop()}</span>{dirty&&<i/>}<button onClick={()=>{setSelected("");setContent("");setSaved("")}}><X size={13}/></button></div>:<div className="cs-no-tab">Select a file from the Explorer</div>}</div>
  {newPath&&<div className="cs-new-file"><input autoFocus value={newPath} onChange={e=>setNewPath(e.target.value)} onKeyDown={e=>e.key==="Enter"&&create()} placeholder="path/to/file.ts"/><button onClick={create}>Create</button><button onClick={()=>setNewPath("")}><X size={15}/></button></div>}
  {selected?<><div className="cs-editor-toolbar"><span>{selected}</span><div><button onClick={remove}><Trash2 size={15}/>Delete</button><button className="primary" disabled={!dirty||saving} onClick={save}><Save size={15}/>{saving?"Saving…":"Save"}</button></div></div><textarea className="cs-code" spellCheck={false} value={content} onChange={e=>setContent(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="s"){e.preventDefault();save()}}}/><div className="cs-statusbar"><span>{dirty?"Unsaved changes":"Saved"}</span><span>{ext(selected).toUpperCase()||"TEXT"}</span><span>{content.length.toLocaleString()} chars</span></div></>:<div className="cs-empty"><Code2 size={42}/><h2>Cookie Code Studio</h2><p>Every tracked repository file can live here as a virtual workspace.</p><span>Choose a file to start editing.</span></div>}</section></div>
  {newPath&&null}
  {memberOpen&&<div className="cs-modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setMemberOpen(false)}><div className="cs-modal"><div className="cs-modal-head"><div><b>Code Studio members</b><span>Google identity is required for developer access.</span></div><button onClick={()=>setMemberOpen(false)}><X size={17}/></button></div><div className="cs-members">{members.map(m=><div className="cs-member" key={m.email}><div className="cs-member-avatar">{m.email[0]?.toUpperCase()}</div><div><b>{m.email}</b><span>{m.role}</span></div></div>)}</div>{owner&&<div className="cs-add"><input value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} placeholder="Illu’s Google email"/><button onClick={addMember}><UserPlus size={15}/>Add developer</button></div>}</div></div>}
 </div>
}