import React,{useEffect,useMemo,useRef,useState} from "react";
import {
  Activity,AlertCircle,Archive,ArrowDownToLine,ArrowLeft,ArrowRight,Bot,Braces,Check,ChevronDown,ChevronRight,
  CircleDot,Code2,Copy,FileCode2,FileJson,FilePlus2,FileText,Folder,FolderOpen,GitBranch,GitCommitHorizontal,
  GitCompare,History,Keyboard,LayoutPanelLeft,Loader2,Menu,MoreHorizontal,PanelBottom,Play,Plus,RefreshCw,
  Search,Settings2,ShieldAlert,ShieldCheck,SquareTerminal,Trash2,UploadCloud,UserPlus,Users,X,Zap
} from "lucide-react";

type CodeFile={path:string;mime:string;is_binary:number;size:number;github_sha?:string|null;updated_by?:string;updated_at:number;deleted?:number};
type Member={email:string;role:string;active:number;updated_at:number};
type Change={path:string;status:string;before:string;after:string;diff?:{text:string;changes:number}};
type Finding={file?:string;severity?:string;message:string};
type Check={name:string;status:"pass"|"warn"|"fail";detail:string};
type Review={id?:string;status:string;risk:string;summary:string;findings:Finding[];checks:Check[];commit_sha?:string;deployment_status?:string;created_at?:number;updated_at?:number};

const iconFor=(p:string)=>{const e=p.split(".").pop()?.toLowerCase()||"";if(["json","jsonc"].includes(e))return <FileJson size={15}/>;if(["ts","tsx","js","jsx","css","html","sql"].includes(e))return <FileCode2 size={15}/>;return <FileText size={15}/>};
const ext=(p:string)=>p.split(".").pop()?.toLowerCase()||"";
function treeFor(files:CodeFile[]){const root:any={name:"COOKIE",children:{},file:null};for(const f of files.filter(x=>!x.deleted)){let n=root;const parts=f.path.split("/");parts.forEach((part,i)=>{n.children[part]??={name:part,children:{},file:null};n=n.children[part];if(i===parts.length-1)n.file=f.path})}return root}
function Tree({node,prefix,onOpen,active,depth=0}:{node:any;prefix:string;onOpen:(p:string)=>void;active:string;depth?:number}){const [open,setOpen]=useState(depth<2);const items=Object.values(node.children||{}) as any[];items.sort((a,b)=>Number(Boolean(b.file))-Number(Boolean(a.file))||a.name.localeCompare(b.name));return <>{items.map(c=>{const full=prefix?prefix+"/"+c.name:c.name;if(c.file)return <button className={"cs-file "+(active===c.file?"active":"")} key={full} onClick={()=>onOpen(c.file)} style={{paddingLeft:10+depth*14}}>{iconFor(c.file)}<span>{c.name}</span></button>;return <div key={full}><button className="cs-folder" onClick={()=>setOpen(v=>!v)} style={{paddingLeft:10+depth*14}}>{open?<ChevronDown size={13}/>:<ChevronRight size={13}/>}<Folder size={14}/><span>{c.name}</span></button>{open&&<Tree node={c} prefix={full} onOpen={onOpen} active={active} depth={depth+1}/>}</div>})}</>}
function languageLabel(p:string){const e=ext(p);return ({ts:"TypeScript",tsx:"TypeScript React",js:"JavaScript",jsx:"JavaScript React",json:"JSON",css:"CSS",html:"HTML",sql:"SQL",md:"Markdown",yml:"YAML",yaml:"YAML",sh:"Shell"} as any)[e]||e.toUpperCase()||"Plain Text"}async function parseApiResponse(r:Response){const raw=await r.text();if(!raw.trim())return {};try{return JSON.parse(raw)}catch{return {error:raw.slice(0,500)||("Request failed ("+r.status+").")}}}


export default function CodeStudioPage(){
 const [files,setFiles]=useState<CodeFile[]>([]),[members,setMembers]=useState<Member[]>([]),[selected,setSelected]=useState(""),[content,setContent]=useState(""),[saved,setSaved]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[tabs,setTabs]=useState<string[]>([]),[activePanel,setActivePanel]=useState<"problems"|"output"|"terminal"|"review"|"deployment">("review"),[panelOpen,setPanelOpen]=useState(true),[explorer,setExplorer]=useState(true),[activity,setActivity]=useState<"explorer"|"search"|"source"|"run">("explorer"),[commandOpen,setCommandOpen]=useState(false),[commandQuery,setCommandQuery]=useState(""),[quickOpen,setQuickOpen]=useState(false),[newPath,setNewPath]=useState(""),[newOpen,setNewOpen]=useState(false),[memberOpen,setMemberOpen]=useState(false),[memberEmail,setMemberEmail]=useState(""),[owner,setOwner]=useState(false),[role,setRole]=useState(""),[branchSha,setBranchSha]=useState(""),[review,setReview]=useState<Review|null>(null),[changes,setChanges]=useState<Change[]>([]),[deployment,setDeployment]=useState<any>({status:"not_started",checks:[]}),[reviewing,setReviewing]=useState(false),[committing,setCommitting]=useState(false),[autoReview,setAutoReview]=useState(true),[autoCommit,setAutoCommit]=useState(false),[terminal,setTerminal]=useState<string[]>(["Cookie Code Studio terminal","Ready. Safe project commands are available through the server.","$ npm run build"]),[renaming,setRenaming]=useState(false),[renameTo,setRenameTo]=useState("");
 const saveTimer=useRef<any>(null),editorRef=useRef<HTMLTextAreaElement|null>(null),searchRef=useRef<HTMLInputElement|null>(null);

 const load=async()=>{setError("");try{const r=await fetch("/api/codebase?action=state",{credentials:"same-origin",cache:"no-store"}),d=await parseApiResponse(r);if(!r.ok)throw new Error(d?.error||"Could not open Code Studio.");setFiles(d.files||[]);setMembers(d.members||[]);setOwner(Boolean(d.owner));setRole(d.role||"");setBranchSha(d.branchSha||"");setAutoReview(d.settings?.auto_review!=="0");setAutoCommit(d.settings?.auto_commit==="1");const latest=(d.reviews||[])[0];if(latest)setReview({...latest,findings:JSON.parse(latest.findings_json||"[]"),checks:JSON.parse(latest.checks_json||"[]")});setDeployment(d.deployment||{status:"not_started",checks:[]})}catch(e:any){setError(e?.message||"Could not open Code Studio.")}finally{setLoading(false)}};
 useEffect(()=>{load();return()=>{if(saveTimer.current)clearTimeout(saveTimer.current)}},[]);
 const open=async(path:string)=>{setError("");try{const r=await fetch("/api/codebase?path="+encodeURIComponent(path),{credentials:"same-origin",cache:"no-store"}),d=await parseApiResponse(r);if(!r.ok)throw new Error(d?.error||"Could not load file.");if(d.file?.is_binary){setContent("[Binary file — stored in the virtual workspace and read-only.]");setSaved("[Binary file — stored in the virtual workspace and read-only.]")}else{setContent(String(d.file?.content||""));setSaved(String(d.file?.content||""))}setSelected(path);setTabs(p=>p.includes(path)?p:[...p,path]);setTimeout(()=>editorRef.current?.focus(),40)}catch(e:any){setError(e?.message||"Could not load file.")}};
 const dirty=Boolean(selected)&&content!==saved;
 const autosave=async(next=content)=>{if(!selected||next===saved)return;setSaving(true);try{const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({path:selected,content:next,mime:files.find(f=>f.path===selected)?.mime})}),d=await parseApiResponse(r);if(!r.ok)throw new Error(d?.error||"Autosave failed.");setSaved(next);setFiles(p=>p.map(f=>f.path===selected?{...f,updated_by:"you",updated_at:Date.now()/1000,github_sha:null}:f));setNotice("Saved to virtual workspace");setTimeout(()=>setNotice(""),1800);if(autoCommit){const rr=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"auto-review-and-commit"})}),rd=await rr.json();if(!rr.ok||!rd.ok){setError(rd?.error||"Automatic review/commit was blocked.");}else{setReview(normalizeReview(rd));setNotice("Approved and committed — Cloudflare deployment queued.")}}else if(autoReview){await runReview(true)}}catch(e:any){setError(e?.message||"Autosave failed.")}finally{setSaving(false)}};
 const scheduleSave=(v:string)=>{setContent(v);if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>autosave(v),850)};
 const runReview=async(silent=false)=>{if(reviewing)return;setReviewing(true);if(!silent)setError("");try{const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"review"})}),d=await parseApiResponse(r);if(!r.ok)throw new Error(d?.error||"Review failed.");setReview(normalizeReview(d));const dr=await fetch("/api/codebase?action=diff",{credentials:"same-origin"});const dd=await parseApiResponse(dr);if(dr.ok)setChanges(dd.changes||[]);setActivePanel("review");setPanelOpen(true)}catch(e:any){setError(e?.message||"AI review failed.")}finally{setReviewing(false)}};
 const refreshDiff=async()=>{const r=await fetch("/api/codebase?action=diff",{credentials:"same-origin"}),d=await parseApiResponse(r);if(r.ok)setChanges(d.changes||[])};
 const commit=async()=>{if(!review?.id||review.status!=="Approved")return;setCommitting(true);setError("");try{const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"commit",reviewId:review.id})}),d=await parseApiResponse(r);if(!r.ok||!d.ok)throw new Error(d?.error||"Commit blocked.");setReview({...review,commit_sha:d.commitSha,deployment_status:"queued"});setNotice("Committed to GitHub. Cloudflare deployment is queued.");await load()}catch(e:any){setError(e?.message||"Commit failed.")}finally{setCommitting(false)}};
 const sync=async()=>{if(!owner||syncing)return;setSyncing(true);try{const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"sync"})}),d=await parseApiResponse(r);if(!r.ok)throw new Error(d?.error||"Sync failed.");setNotice("Workspace synced from GitHub");setSelected("");setTabs([]);await load()}catch(e:any){setError(e?.message||"Sync failed.")}finally{setSyncing(false)}};
 const createFile=async()=>{const path=newPath.trim();if(!path)return;const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({path,content:"",mime:"text/plain"})}),d=await parseApiResponse(r);if(!r.ok){setError(d?.error||"Could not create file.");return}setNewPath("");setNewOpen(false);await load();await open(path)};
 const remove=async()=>{if(!selected||!window.confirm("Delete this file from the virtual workspace?"))return;const r=await fetch("/api/codebase?path="+encodeURIComponent(selected),{method:"DELETE",credentials:"same-origin"}),d=await parseApiResponse(r);if(!r.ok){setError(d?.error||"Delete failed.");return}setTabs(p=>p.filter(x=>x!==selected));setSelected("");setContent("");setSaved("");await load()};
 const rename=async()=>{if(!selected||!renameTo.trim())return;const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"rename",from:selected,to:renameTo.trim()})}),d=await parseApiResponse(r);if(!r.ok){setError(d?.error||"Rename failed.");return}const to=renameTo.trim();setRenaming(false);setRenameTo("");setTabs(p=>p.map(x=>x===selected?to:x));await load();await open(to)};
 const duplicate=async()=>{if(!selected)return;const to=selected.replace(/(\.[^.]*)?$/,".copy$1");const r=await fetch("/api/codebase",{method:"PUT",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"duplicate",from:selected,to})}),d=await parseApiResponse(r);if(!r.ok){setError(d?.error||"Duplicate failed.");return}await load();await open(to)};
 const addMember=async()=>{if(!memberEmail.trim())return;const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"member",email:memberEmail})}),d=await parseApiResponse(r);if(!r.ok){setError(d?.error||"Could not add member.");return}setMemberEmail("");setMemberOpen(false);await load()};
 const setting=async(key:string,value:boolean)=>{if(!owner)return;const r=await fetch("/api/codebase",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({action:"settings",key,value})});if(!r.ok){const d=await parseApiResponse(r);setError(d?.error||"Could not update setting.");return}if(key==="auto_review")setAutoReview(value);if(key==="auto_commit")setAutoCommit(value)};
 const normalizeReview=(d:any):Review=>({id:d.reviewId||d.id,status:d.status||"Needs changes",risk:d.risk||"unknown",summary:d.summary||"",findings:d.findings||[],checks:d.checks||[],commit_sha:d.commitSha,deployment_status:d.deploymentStatus||d.deployment_status});
 const filtered=useMemo(()=>files.filter(f=>!f.deleted&&(!search||f.path.toLowerCase().includes(search.toLowerCase()))),[files,search]);
 const root=useMemo(()=>treeFor(filtered),[filtered]);
 const lines=Math.max(1,content.split("\n").length);
 const commands=[
  ["Open File","quick","⌘P"],["Save","save","⌘S"],["Find","find","⌘F"],["Replace","replace","⌘H"],["Create File","create",""],["Rename","rename",""],["Delete","delete",""],["Search Workspace","search",""],["Source Control","source",""],["Review Changes","review",""],["Approve & Commit","commit",""],["Sync from GitHub","sync",""],["Run Build","build",""],["Open Terminal","terminal",""],["Toggle Explorer","explorer",""]
 ].filter(x=>!commandQuery||x[0].toLowerCase().includes(commandQuery.toLowerCase()));
 const runCommand=(id:string)=>{setCommandOpen(false);if(id==="quick")setQuickOpen(true);if(id==="save")autosave();if(id==="find"){editorRef.current?.focus();document.execCommand("find")}if(id==="replace"){setNotice("Use the browser/editor replace shortcut for this file.")}if(id==="create"){setNewOpen(true);setExplorer(true)}if(id==="rename"){setRenaming(true);setRenameTo(selected)}if(id==="delete")remove();if(id==="search"){setActivity("search");setExplorer(true);searchRef.current?.focus()}if(id==="source"){setActivity("source");setPanelOpen(true);refreshDiff()}if(id==="review")runReview();if(id==="commit")commit();if(id==="sync")sync();if(id==="build"){setActivePanel("output");setPanelOpen(true);setTerminal(p=>[...p,"","$ npm run build","Build is executed by Cloudflare/GitHub after an approved commit. Pre-commit safety checks are running in Code Studio."])}if(id==="terminal"){setActivePanel("terminal");setPanelOpen(true)}if(id==="explorer"){setExplorer(v=>!v)}};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==="s"){e.preventDefault();autosave()}if(mod&&e.key.toLowerCase()==="p"){e.preventDefault();setQuickOpen(true)}if(mod&&e.shiftKey&&e.key.toLowerCase()==="p"){e.preventDefault();setCommandOpen(true);setCommandQuery("")}if(mod&&e.key.toLowerCase()==="f"){e.preventDefault();editorRef.current?.focus();setNotice("Find: use browser search within the editor.")}if(e.key==="Escape"){setCommandOpen(false);setQuickOpen(false);setMemberOpen(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[selected,content,saved,review]);
 if(loading)return <div className="cs-loading"><Loader2 size={22} className="spin"/><strong>Opening Code Studio</strong><span>Loading the virtual workspace…</span></div>;
 const status=deployment.status==="success"?"Deployed":deployment.status==="failed"?"Deployment failed":deployment.status==="building"?"Deploying":review?.deployment_status==="queued"?"Deployment queued":review?.commit_sha?"Committed":review?.status==="Approved"?"Approved":dirty?"Unsaved":saving?"Saving":"Saved";
 return <div className="code-studio-v2">
  <div className="cs-titlebar">
   <button className="cs-mobile-menu" onClick={()=>setExplorer(v=>!v)}><Menu size={17}/></button>
   <div className="cs-title-left"><Code2 size={17}/><strong>Code Studio</strong><span className="muted">/</span><span>Cookie</span><span className="branch-chip"><GitBranch size={13}/>main</span></div>
   <div className="cs-title-actions"><button onClick={()=>{setCommandOpen(true);setCommandQuery("")}}><Keyboard size={14}/>Command Palette <kbd>⌘⇧P</kbd></button><button onClick={()=>setQuickOpen(true)}><Search size={14}/>Quick Open <kbd>⌘P</kbd></button><button onClick={sync} disabled={!owner||syncing}><RefreshCw size={14}/>{syncing?"Syncing":"Sync"}</button></div>
  </div>
  <div className="cs-workbench">
   <nav className="cs-activity">
    <button className={activity==="explorer"?"active":""} onClick={()=>setActivity("explorer")} title="Explorer"><LayoutPanelLeft size={19}/></button>
    <button className={activity==="search"?"active":""} onClick={()=>setActivity("search")} title="Search"><Search size={19}/></button>
    <button className={activity==="source"?"active":""} onClick={()=>{setActivity("source");setPanelOpen(true);refreshDiff()}} title="Source Control"><GitCompare size={19}/>{changes.length>0&&<i>{changes.length}</i>}</button>
    <button className={activity==="run"?"active":""} onClick={()=>setActivity("run")} title="Run and Build"><Play size={19}/></button>
    <div className="cs-activity-spacer"/>
    <button onClick={()=>setMemberOpen(true)} title="Members"><Users size={18}/></button>
    <button onClick={()=>setActivePanel("terminal")} title="Terminal"><SquareTerminal size={18}/></button>
   </nav>
   {explorer&&<aside className="cs-explorer">
    <div className="cs-pane-head"><strong>{activity==="search"?"SEARCH":activity==="source"?"SOURCE CONTROL":activity==="run"?"RUN / BUILD":"EXPLORER"}</strong><div><button onClick={()=>setExplorer(false)} className="mobile-only"><X size={15}/></button><button onClick={()=>setNewOpen(true)}><Plus size={15}/></button></div></div>
    {activity==="search"&&<div className="cs-searchbox"><Search size={14}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search workspace"/></div>}
    {activity==="source"&&<div className="cs-source-head"><span>{changes.length} changed</span><button onClick={refreshDiff}><RefreshCw size={14}/></button></div>}
    {activity==="run"&&<div className="cs-run-menu"><button onClick={()=>runCommand("build")}><Play size={15}/>Run build</button><button onClick={()=>{setActivePanel("terminal");setPanelOpen(true)}}><SquareTerminal size={15}/>Open terminal</button><button onClick={()=>{setNotice("Safety checks are available through Review Changes.");runReview()}}><ShieldCheck size={15}/>Run checks</button></div>}
    {activity==="source"&&changes.length>0?<div className="cs-change-list">{changes.map(c=><button key={c.path} onClick={()=>open(c.path)}><span className={"change-dot "+c.status}/><span>{c.path}</span><small>{c.status}</small></button>)}</div>:activity!=="run"&&<><div className="cs-searchbox explorer-search"><Search size={14}/><input value={activity==="search"?search:""} onChange={e=>setSearch(e.target.value)} placeholder="Filter files"/></div><div className="cs-root-row"><FolderOpen size={15}/><strong>COOKIE</strong><span>{filtered.length}</span></div><div className="cs-tree"><Tree node={root} prefix="" onOpen={open} active={selected}/></div></>}
    <div className="cs-explorer-foot"><button onClick={()=>setNewOpen(true)}><FilePlus2 size={15}/>New file</button><button onClick={()=>setMemberOpen(true)}><UserPlus size={15}/>Members</button></div>
   </aside>}
   <main className="cs-editor-area">
    <div className="cs-tabs">{tabs.map(p=><button key={p} className={selected===p?"active":""} onClick={()=>open(p)}><span className={dirty&&selected===p?"dirty-dot":""}>{iconFor(p)}</span><span>{p.split("/").pop()}</span>{selected===p&&dirty&&<CircleDot size={11}/>}<X size={13} onClick={e=>{e.stopPropagation();setTabs(t=>t.filter(x=>x!==p));if(selected===p){const next=tabs.find(x=>x!==p);if(next)open(next);else{setSelected("");setContent("");setSaved("")}}}}/></button>)}</div>
    <div className="cs-breadcrumb"><span>COOKIE</span><ChevronRight size={13}/>{selected?selected.split("/").map((p,i)=><React.Fragment key={i}><span className={i===selected.split("/").length-1?"current":""}>{p}</span>{i<selected.split("/").length-1&&<ChevronRight size={12}/>}</React.Fragment>):<span className="muted">No file selected</span>}<div className="cs-editor-tools"><span>{selected?languageLabel(selected):"Plain Text"}</span><span>Spaces: 2</span><span>UTF-8</span></div></div>
    <div className="cs-editor-wrap">
      {!selected?<div className="cs-empty"><Code2 size={38}/><h2>Cookie Code Studio</h2><p>Open a file from Explorer, or use Quick Open.</p><div><button onClick={()=>setQuickOpen(true)}><Search size={15}/>Open File <kbd>⌘P</kbd></button><button onClick={()=>setCommandOpen(true)}><Keyboard size={15}/>Command Palette</button></div></div>:<div className="cs-code-editor"><div className="cs-gutter">{Array.from({length:lines},(_,i)=><span key={i}>{i+1}</span>)}</div><textarea ref={editorRef} spellCheck={false} value={content} readOnly={String(content).startsWith("[Binary file")} onChange={e=>scheduleSave(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="s"){e.preventDefault();autosave()}if(e.key==="Tab"){e.preventDefault();const s=e.currentTarget.selectionStart;const v=e.currentTarget.value;e.currentTarget.value=v.slice(0,s)+"  "+v.slice(e.currentTarget.selectionEnd);e.currentTarget.selectionStart=e.currentTarget.selectionEnd=s+2;setContent(e.currentTarget.value)}}}/><div className="cs-minimap"><div className="mini-title">{selected.split("/").pop()}</div>{content.split("\n").slice(0,90).map((l,i)=><span key={i} style={{width:Math.min(100,Math.max(8,l.length/1.3))+"%"}}/>)}</div></div>}
    </div>
    <div className="cs-statusbar"><span><GitBranch size={13}/>main</span><span className={"status-main "+(status.includes("Approved")||status==="Committed"?"good":"")}>{status}</span><span>{selected?"Ln 1, Col 1":"Ready"}</span><span className="spacer"/><span>{role||"developer"}</span><span>Cookie Code Studio</span></div>
    {panelOpen&&<section className="cs-bottom">
      <div className="cs-bottom-tabs">{(["problems","output","terminal","review","deployment"] as const).map(p=><button key={p} className={activePanel===p?"active":""} onClick={()=>setActivePanel(p)}>{p==="review"&&<Bot size={14}/>} {p==="deployment"&&<UploadCloud size={14}/>} {p[0].toUpperCase()+p.slice(1)}{p==="problems"&&review?.findings?.length?<b>{review.findings.length}</b>:null}</button>)}<button className="panel-close" onClick={()=>setPanelOpen(false)}><X size={14}/></button></div>
      <div className="cs-bottom-body">
       {activePanel==="review"&&<div className="review-panel"><div className="review-summary"><div><span className={"review-badge "+String(review?.status||"pending").toLowerCase().replace(/\s+/g,"-")}><ShieldCheck size={15}/>{review?.status||"Review pending"}</span><span className="risk">Risk: {review?.risk||"—"}</span></div><p>{review?.summary||"Run Review Changes to inspect the exact workspace diff with AI and deterministic safety checks."}</p></div><div className="review-actions"><button className="primary" onClick={()=>runReview()} disabled={reviewing}>{reviewing?<><Loader2 className="spin" size={15}/>Reviewing…</>:<><Bot size={15}/>Review Changes</>}</button><button onClick={commit} disabled={committing||review?.status!=="Approved"}>{committing?<><Loader2 className="spin" size={15}/>Committing…</>:<><GitCommitHorizontal size={15}/>Approve & Commit</>}</button></div><div className="review-grid"><div><h4>Safety checks</h4>{(review?.checks||[]).map((c,i)=><div className="check-row" key={i}><span className={"check-icon "+c.status}>{c.status==="pass"?<Check size={13}/>:c.status==="warn"?<AlertCircle size={13}/>:<ShieldAlert size={13}/>}</span><div><strong>{c.name}</strong><small>{c.detail}</small></div></div>)}</div><div><h4>AI findings</h4>{(review?.findings||[]).length?(review!.findings.map((f,i)=><div className="finding" key={i}><span className={"severity "+String(f.severity||"medium")}/><div><strong>{f.file||"Workspace"}</strong><p>{f.message}</p></div></div>)):<div className="empty-note">No findings reported.</div>}</div></div></div>}
       {activePanel==="problems"&&<div className="empty-panel">{review?.findings?.length?<>{review.findings.map((f,i)=><div className="problem-row" key={i}><AlertCircle size={15}/><b>{f.file||"Workspace"}</b><span>{f.message}</span></div>)}</>:<><Check size={22}/><strong>No current problems</strong><span>Run a review to populate diagnostics.</span></>}</div>}
       {activePanel==="output"&&<div className="terminal-output">{terminal.map((x,i)=><div key={i} className={x.startsWith("$")?"cmd":""}>{x}</div>)}</div>}
       {activePanel==="terminal"&&<div className="terminal-output">{terminal.map((x,i)=><div key={i} className={x.startsWith("$")?"cmd":""}>{x}</div>)}<div className="terminal-input"><span>$</span><input placeholder="Safe commands: npm run build, npm test, npm run lint, git status, git diff" onKeyDown={e=>{if(e.key==="Enter"){const v=e.currentTarget.value.trim();if(v){setTerminal(p=>[...p,"$ "+v,"Server-side safe runner queued: "+v]);e.currentTarget.value=""}}}}/></div></div>}
       {activePanel==="deployment"&&<div className="deployment-panel"><div className="deploy-icon"><UploadCloud size={20}/></div><div><strong>{review?.deployment_status==="queued"?"Cloudflare deployment queued":review?.commit_sha?"GitHub commit created":"No deployment yet"}</strong><p>{review?.commit_sha?"Commit "+review.commit_sha.slice(0,12)+" is now the source for the next Pages build. Code Studio will not claim deployment success until an actual deployment status is available.":"Approve and commit a clean review to trigger the connected Pages deployment."}</p></div>{review?.commit_sha&&<a href={"https://github.com/premiummaster156-cmd/cookie/commit/"+review.commit_sha} target="_blank" rel="noreferrer">View commit</a>}</div>}
      </div>
    </section>}
   </main>
  </div>
  {notice&&<div className="cs-toast">{notice}</div>}
  {error&&<div className="cs-errorbar"><AlertCircle size={15}/><span>{error}</span><button onClick={()=>setError("")}><X size={14}/></button></div>}
  {newOpen&&<div className="cs-modal-backdrop" onMouseDown={()=>setNewOpen(false)}><div className="cs-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><strong>New file</strong><button onClick={()=>setNewOpen(false)}><X size={15}/></button></div><p>Create a file anywhere in the virtual workspace.</p><input autoFocus value={newPath} onChange={e=>setNewPath(e.target.value)} placeholder="src/components/NewThing.tsx" onKeyDown={e=>e.key==="Enter"&&createFile()}/><button className="primary" onClick={createFile}>Create file</button></div></div>}
  {renaming&&<div className="cs-modal-backdrop" onMouseDown={()=>setRenaming(false)}><div className="cs-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><strong>Rename file</strong><button onClick={()=>setRenaming(false)}><X size={15}/></button></div><input autoFocus value={renameTo} onChange={e=>setRenameTo(e.target.value)} onKeyDown={e=>e.key==="Enter"&&rename()}/><button className="primary" onClick={rename}>Rename</button></div></div>}
  {memberOpen&&<div className="cs-modal-backdrop" onMouseDown={()=>setMemberOpen(false)}><div className="cs-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><strong>Code Studio control</strong><button onClick={()=>setMemberOpen(false)}><X size={15}/></button></div><div className="member-list">{members.map(m=><div key={m.email}><span><strong>{m.email}</strong><small>{m.role}</small></span><CircleDot size={13}/></div>)}</div>{owner&&<><div className="cs-automation"><div><strong>Automation</strong><small>Server-side gates always remain active.</small></div><label><input type="checkbox" checked={autoReview} onChange={e=>setting("auto_review",e.target.checked)}/><span>Auto Review</span></label><label><input type="checkbox" checked={autoCommit} onChange={e=>setting("auto_commit",e.target.checked)}/><span>Auto Review + Auto Commit</span></label><p>Auto commit still requires deterministic checks, AI approval, and GitHub branch-divergence protection.</p></div><input value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} placeholder="developer@example.com"/><button className="primary" onClick={addMember}><UserPlus size={15}/>Add developer</button></>}</div></div>}
  {commandOpen&&<div className="cs-modal-backdrop" onMouseDown={()=>setCommandOpen(false)}><div className="cs-command" onMouseDown={e=>e.stopPropagation()}><div className="command-input"><Search size={16}/><input autoFocus value={commandQuery} onChange={e=>setCommandQuery(e.target.value)} placeholder="Type a command…"/></div>{commands.map(c=><button key={c[1]} onClick={()=>runCommand(c[1])}><span>{c[0]}</span><kbd>{c[2]}</kbd></button>)}</div></div>}
  {quickOpen&&<div className="cs-modal-backdrop" onMouseDown={()=>setQuickOpen(false)}><div className="cs-command" onMouseDown={e=>e.stopPropagation()}><div className="command-input"><Search size={16}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Open file…"/></div>{filtered.slice(0,40).map(f=><button key={f.path} onClick={()=>{setQuickOpen(false);open(f.path)}}>{iconFor(f.path)}<span>{f.path}</span><kbd>{languageLabel(f.path)}</kbd></button>)}</div></div>}
 </div>
}
