import React,{useEffect,useMemo,useState} from "react";
import {BookOpen,ChevronRight,CircleHelp,FileText,LockKeyhole,MessageSquare,Search,ShieldCheck,Sparkles,Upload,UserRound,Volume2,Wrench,X} from "lucide-react";
type Article={id:string;title:string;summary:string;body:React.ReactNode};
type Topic={id:string;title:string;description:string;icon:React.ReactNode;articles:Article[]};
const topics:Topic[]=[
{id:"start",title:"Getting started",description:"The essentials for using Cookie.",icon:<Sparkles size={18}/>,articles:[
{id:"start-cookie",title:"What is Cookie?",summary:"A quick overview of Cookie and what it can do.",body:<><p>Cookie is an AI workspace for conversations, research, files, coding, projects, and focused work.</p><h3>Start here</h3><ol><li>Open a new chat and describe what you need.</li><li>Attach a file or image when the task needs it.</li><li>For larger goals, use <b>Work</b> so Cookie can structure the task.</li></ol><p>You do not need to choose a tool first. Cookie can decide when a task needs search, calculation, file analysis, or other capabilities.</p></>},
{id:"first-chat",title:"Start your first chat",summary:"Get useful answers with a clear prompt.",body:<><p>Tell Cookie the goal, relevant context, and the format you want back.</p><h3>A useful prompt</h3><p>Say what you are trying to accomplish, include important constraints, and mention the audience or deadline when it matters.</p><p>You can ask Cookie to revise an answer instead of starting over.</p></>}
]},
{id:"account",title:"Account & login",description:"Sign in, profile, password, and account access.",icon:<UserRound size={18}/>,articles:[
{id:"login",title:"Sign in and account access",summary:"How Cookie accounts and access work.",body:<><p>Your account keeps your Cookie identity and account-level settings together. Use the sign-in flow shown by Cookie and keep access to your email address.</p><h3>Locked or restricted accounts</h3><p>An account can be restricted for security or moderation reasons. Cookie may show the reason and, for temporary restrictions, when access can return.</p></>},
{id:"password",title:"Reset your password",summary:"Use the secure reset email when you cannot sign in.",body:<><p>Use the password reset option on the sign-in screen. Cookie sends a time-limited reset link to the account email when available.</p><p>Never share a reset link or verification code with another person.</p></>}
]},
{id:"chat",title:"Chats",description:"Conversations, history, sharing, and temporary chats.",icon:<MessageSquare size={18}/>,articles:[
{id:"history",title:"Chat history",summary:"Manage conversations from the sidebar.",body:<><p>Your saved conversations appear in the sidebar. You can open, rename, pin, archive, or delete conversations where those controls are available.</p><p>Deleting a chat removes it from your Cookie chat history. Some security, billing, or moderation records may be kept separately when required for legitimate purposes.</p></>},
{id:"temporary",title:"Temporary chats",summary:"Use a chat when you do not want it in normal history.",body:<><p>Temporary chats are designed for conversations you do not want saved to normal chat history. Do not treat temporary mode as a promise of zero server-side processing or immediate deletion of every technical record.</p></>},
{id:"sharing",title:"Share a conversation",summary:"Create a read-only view of a conversation.",body:<><p>Shared conversations can be viewed by anyone who has the share link. Only share information you are comfortable exposing through that link.</p><p>Remove sharing when you no longer want the link to work, where that control is available.</p></>}
]},
{id:"models",title:"Models & responses",description:"Choosing models, effort, and getting better results.",icon:<BookOpen size={18}/>,articles:[
{id:"models",title:"Cookie models",summary:"Understand the model levels available in Cookie.",body:<><p>Cookie can offer different model levels for different plans. Higher levels may provide more reasoning depth, multimodal capability, or engineering performance.</p><p>Availability, limits, and model names can change as Cookie is updated.</p></>},
{id:"better-results",title:"Get better answers",summary:"Simple ways to improve results.",body:<><ul><li>Give Cookie the actual goal, not only the topic.</li><li>Include constraints and examples.</li><li>Ask for a specific output format.</li><li>Attach source material when accuracy depends on it.</li><li>Correct a wrong assumption and ask Cookie to continue.</li></ul></>}
]},
{id:"work",title:"Work & projects",description:"Longer tasks, projects, and organized work.",icon:<Wrench size={18}/>,articles:[
{id:"work-mode",title:"Use Work for larger goals",summary:"Let Cookie break a goal into steps.",body:<><p>Work is designed for tasks that involve several steps. Describe the outcome you want and let Cookie determine a practical workflow.</p><p>Review important outputs before using them in production or making consequential decisions.</p></>},
{id:"projects",title:"Projects",summary:"Keep related work together.",body:<><p>Use Projects to keep related conversations and work in one place. The exact project features available to you depend on the current Cookie release and account plan.</p></>}
]},
{id:"files",title:"Files & images",description:"Upload files, analyze documents, and work with images.",icon:<Upload size={18}/>,articles:[
{id:"uploads",title:"Upload a file",summary:"Give Cookie the material it needs for a task.",body:<><p>Use the attachment control in the composer to add supported files or images. Tell Cookie what you want it to do with the upload.</p><h3>Before uploading</h3><p>Remove sensitive information you do not need to share. File size and supported formats can vary by feature and plan.</p></>},
{id:"images",title:"Images",summary:"Ask Cookie to understand or create visual content.",body:<><p>Cookie can analyze supported images and, where enabled, generate images. Describe the visual result or the exact parts of an image you want analyzed.</p></>}
]},
{id:"search",title:"Search & research",description:"Current information, sources, and research workflows.",icon:<Search size={18}/>,articles:[
{id:"web",title:"When Cookie searches the web",summary:"Cookie can decide when live information is needed.",body:<><p>You do not need to manually select a search tool. Cookie can decide that a question needs current web information and use search when that capability is available.</p><p>For important claims, open the cited sources and verify the details yourself.</p></>},
{id:"sources",title:"Sources and citations",summary:"Understand where research answers come from.",body:<><p>When a response includes sources, use the source links and inspector to review the supporting material. A citation does not guarantee that every statement is correct, so check important facts at the original source.</p></>}
]},
{id:"memory",title:"Memory",description:"How saved preferences and memory work.",icon:<CircleHelp size={18}/>,articles:[
{id:"memory",title:"How Memory works",summary:"Cookie can retain useful information when Memory is enabled.",body:<><p>Memory can help Cookie use relevant information from previous interactions so you do not have to repeat it.</p><p>Review memory regularly. Do not save passwords, security codes, or other secrets as memory.</p></>},
{id:"memory-controls",title:"Control your Memory",summary:"Review or remove saved memory.",body:<><p>Use Cookie's Memory settings to review saved items and remove information you no longer want retained as memory. Deleting a memory does not necessarily delete the original conversation or other copies of the information.</p></>}
]},
{id:"voice",title:"Voice",description:"Talk with Cookie using your microphone.",icon:<Volume2 size={18}/>,articles:[
{id:"voice",title:"Use Voice",summary:"Start and manage a voice conversation.",body:<><p>Open Voice and allow microphone access when your device asks. Speak naturally and pause when you want Cookie to respond.</p><p>Voice availability and limits can vary by device, account, and plan.</p></>}
]},
{id:"code",title:"Code Studio",description:"Build, edit, review, and manage code safely.",icon:<Wrench size={18}/>,articles:[
{id:"code-studio",title:"Code Studio basics",summary:"Work with a codebase without losing control.",body:<><p>Code Studio is designed for engineering work such as inspecting files, making changes, reviewing revisions, and validating code.</p><p>Review changes before deployment. Never place API keys, passwords, or private tokens in source files.</p></>},
{id:"protected",title:"Protected files and revisions",summary:"Why some project files have extra protection.",body:<><p>Some files and configuration areas are protected to reduce accidental damage. Use revisions and review changes before accepting important modifications.</p></>}
]},
{id:"gpts",title:"GPTs",description:"Specialized assistants inside Cookie.",icon:<Sparkles size={18}/>,articles:[
{id:"gpts",title:"Use GPTs",summary:"Choose a specialized assistant for a task.",body:<><p>GPTs are specialized Cookie experiences with focused instructions, such as study, coding, writing, research, data, or creative work.</p><p>Choose one when its specialization matches your task. You can return to normal Chat at any time.</p></>}
]},
{id:"billing",title:"Plans & billing",description:"Plans, limits, and account usage.",icon:<FileText size={18}/>,articles:[
{id:"plans",title:"Plans and limits",summary:"Why features and limits can differ by account.",body:<><p>Cookie plans can have different model access, usage limits, and features. Limits may change as the service evolves.</p><p>Your account settings are the best place to see the plan and limits currently applied to you.</p></>}
]},
{id:"safety",title:"Safety & moderation",description:"Account restrictions and keeping Cookie safe.",icon:<ShieldCheck size={18}/>,articles:[
{id:"moderation",title:"Warnings, suspensions, and bans",summary:"What account restrictions mean.",body:<><p>Cookie may warn, temporarily suspend, or permanently restrict accounts that violate the Terms or abuse the service.</p><p>Temporary restrictions can include an end time. Permanent restrictions can require an administrator decision before access is restored.</p></>},
{id:"safe-use",title:"Safe use",summary:"Use Cookie responsibly.",body:<><p>Do not use Cookie to harm people, commit fraud, evade security controls, or create dangerous or illegal content. Do not rely on Cookie alone for medical, legal, financial, or other high-stakes decisions.</p></>}
]},
{id:"privacy",title:"Privacy & data",description:"Understand the basics of your data and privacy.",icon:<LockKeyhole size={18}/>,articles:[
{id:"privacy",title:"Privacy basics",summary:"What to know before using Cookie.",body:<><p>Cookie processes information needed to provide the service, including account information and content you choose to submit. Some features may create additional technical, security, or moderation records.</p><p>Read the <button className="help-inline-link" onClick={()=>window.dispatchEvent(new CustomEvent("cookie:open-legal",{detail:"privacy"}))}>Privacy Policy</button> for the full explanation.</p></>}
]},
{id:"troubleshoot",title:"Troubleshooting",description:"Fix common problems quickly.",icon:<CircleHelp size={18}/>,articles:[
{id:"not-working",title:"Cookie is not responding",summary:"What to check when a request fails.",body:<><ol><li>Check your internet connection.</li><li>Refresh Cookie and retry.</li><li>Try a new chat if the conversation is very large.</li><li>For uploads, confirm the file is supported and not too large.</li><li>If the problem persists, check for a service notice or contact support.</li></ol></>},
{id:"browser",title:"Browser or mobile issues",summary:"Quick fixes for Safari and mobile devices.",body:<><p>Refresh the page, make sure your browser is up to date, and confirm Cookie has the permissions it needs for features such as microphone access. On iPhone, use the latest supported iOS and Safari version available to you.</p></>}
]}
];
function TopicOverview({topic,onArticle}:{topic:Topic;onArticle:(a:Article)=>void}){
  const articleNames=topic.articles.map(a=>a.title).join(", ");
  const focus:string=({
    start:"Use this area to build a reliable mental model of Cookie before you depend on it. Start with the basic chat workflow, then learn how attachments, Work, models, and settings change the way a task is handled. A strong first interaction usually names the outcome, supplies the context Cookie cannot infer, identifies constraints, and asks for a concrete format. For important work, keep the original source material available so you can compare Cookie's answer with the evidence.",
    account:"This area covers the identity and security layer around Cookie. Your account is the boundary that connects your profile, sign-in state, plan, credits, settings, conversations, projects, Memory, and other account-scoped data. Treat passwords, verification codes, reset links, and active sessions as secrets. If access looks wrong, stop changing unrelated settings and use the normal recovery path so support can distinguish an account problem from a product problem.",
    chat:"Chats are the main working surface in Cookie, but a conversation has more lifecycle states than simply 'open' or 'closed'. History, temporary chats, archived conversations, pinned items, shared links, attachments, generated files, and model choices can affect what you see later. Learn what each control actually does before using it for sensitive or important work, and remember that deleting a visible conversation is not automatically the same thing as erasing every operational record.",
    models:"Model choice should follow the task rather than a desire to select the largest label. Faster models can be appropriate for simple drafting or everyday questions; deeper models can be useful for complex reasoning, engineering, analysis, or multimodal work when your plan allows them. Regardless of model, provide the information that determines correctness. A more capable model can still produce a confident mistake when the source material or constraints are incomplete.",
    work:"Work and Projects are intended for goals that have several dependent steps. Instead of treating a large task as one giant prompt, define the desired outcome, identify important inputs, let Cookie organize the work, and review intermediate decisions. Projects are useful when context needs to stay together over time. For production changes, financial decisions, public publishing, or other consequential outcomes, keep a human review step before execution.",
    files:"Files and images turn Cookie from a text-only conversation into a workspace for source material. Upload only what the task needs, describe what you want extracted or changed, and distinguish the original document from Cookie's interpretation. File parsing can introduce omissions or formatting errors, and images can contain information that is easy to overlook. Keep sensitive documents to the minimum necessary and verify important extracted values against the original.",
    search:"Search and research are about evidence, not simply producing a longer answer. A useful research workflow identifies the exact question, separates current facts from background knowledge, compares sources, checks dates and definitions, and states uncertainty. When Cookie supplies citations, open the underlying sources for important claims. A source can be authoritative without proving every sentence in a generated answer, so treat citations as a path to evidence rather than a substitute for verification.",
    memory:"Memory is designed to reduce repetition by allowing relevant information to persist beyond a single conversation. The useful boundary is relevance: preferences, recurring goals, or stable working context can help; passwords, authentication codes, private keys, and unnecessary sensitive details should not be treated as convenient memory. Review saved information periodically and remember that removing a memory item does not necessarily remove the conversation or another copy where the same information appeared.",
    voice:"Voice changes the interaction mode, not the need for clear intent. A good voice session states the goal early, gives Cookie enough context, and uses short corrections when the conversation drifts. Microphone permissions, device audio routing, network quality, model availability, and account limits can affect the experience. For important information, use the resulting text or source material as the record you verify rather than relying only on a spoken response.",
    code:"Code Studio is an engineering workspace, so correctness includes architecture, security, maintainability, and verification—not only whether a file changed. Inspect the existing code before editing, understand dependencies, preserve protected boundaries, review diffs, and run the relevant checks before deployment. Never place credentials in source code. When an automated change touches authentication, databases, deployment, or security controls, treat the review step as mandatory rather than optional.",
    gpts:"GPTs are specialized starting points with focused instructions and different intended uses. Pick a specialist when its role matches the task, but remember that specialization does not remove the need for good context or verification. A coding GPT still needs the actual repository constraints; a research GPT still needs source checking; a writing GPT still needs the audience and desired voice. Return to normal Chat when a task no longer benefits from the specialist's focus.",
    billing:"Plans and billing determine which models, limits, and capabilities an account can use. The important distinction is between a product feature existing and that feature being available to your particular account at a particular moment. Check the account and Settings surfaces before assuming access. Do not attempt to work around a plan limit through account rotation, unsupported requests, or manipulation of client-side values; use the supported upgrade or support path instead.",
    safety:"Safety and moderation protect both the service and the people using it. A restriction can result from security signals, abusive behavior, prohibited activity, or other service-rule concerns, and a temporary restriction can have a defined end time. Use Cookie for legitimate purposes, do not attempt to bypass enforcement, and do not rely on an AI response as permission to perform a harmful or unauthorized action. High-impact decisions still require appropriate human judgment and primary sources.",
    privacy:"Privacy is easiest to protect before information is submitted. Ask what Cookie needs for the task, remove unnecessary identifiers or secrets, understand whether the action creates a saved record or shareable output, and use the available data controls afterward. Account data, chat content, files, Memory, projects, security records, and shared links can have different lifecycles. For the complete explanation of processing and choices, use the Privacy Policy linked below.",
    troubleshoot:"Troubleshooting works best when you isolate the failure instead of repeatedly changing unrelated settings. Identify whether the problem is authentication, a particular conversation, an upload, search, voice, Code Studio, or the service itself. Capture the visible error and the step that caused it, retry once after a refresh, and then use the appropriate support route. Avoid deleting useful evidence or changing security settings merely because a request failed."
  } as Record<string,string>)[topic.id] || "Use this topic to understand how the related Cookie features work, what information they need, what controls you have, and what should be verified before you rely on an important result.";

  const blocks=[
    ["What this topic covers",focus],
    ["A practical workflow",`Start by choosing the smallest Cookie feature that matches the outcome. Review the topic articles (${articleNames}) before a complex task, then provide the goal, relevant context, constraints, and desired output. Work in small verifiable steps when the task is consequential. After Cookie responds, check the parts that matter: source accuracy, permissions, account state, files, generated changes, or external effects. If the first result is incomplete, explain exactly what is missing and continue from the existing context rather than silently assuming the missing information.`],
    ["What to prepare",`Before using this area, decide what information Cookie actually needs. Prepare the original source or evidence when accuracy matters, remove secrets and unnecessary personal information, and identify any deadline, audience, technical constraint, or policy that should shape the result. If the task affects an account, project, deployment, shared link, or stored data, make sure you understand which control will change that state. Preparation reduces both incorrect answers and accidental actions.`],
    ["Common mistakes",`The most common failure is asking Cookie to infer a constraint that was never supplied. Other mistakes include treating generated text as verified fact, uploading an entire sensitive document when only one section is needed, assuming a visible button guarantees a server-side action succeeded, confusing temporary behavior with permanent deletion, or selecting a model based only on its name. When something matters, verify the result against the original source and confirm the resulting account or workspace state.`],
    ["Privacy and security",`Use the minimum information necessary for the task. Never paste passwords, one-time verification codes, private keys, session tokens, or other authentication secrets into prompts, files, Memory, or shared conversations. Be especially careful with documents containing other people's personal information or confidential business material. If you share a conversation or generated artifact, assume the recipient can see the information contained in that share. Use Settings, chat controls, and account security controls when they match the action you need.`],
    ["When something goes wrong",`First identify the exact boundary where the failure occurred: did the page fail to load, did authentication fail, did the request fail, did the output contain an error, or did the requested state change not persist? Refreshing can resolve transient client state, while a new chat can isolate conversation-specific problems. For files, verify format and size. For account problems, use the recovery flow rather than creating duplicate accounts. For Code Studio, inspect the diff and checks. For privacy or moderation questions, use the relevant policy and support route.`],
    ["How to get better results",`A high-quality request is specific without being unnecessarily long. State the desired outcome first, then provide the facts Cookie must know, constraints it must respect, and the format you want returned. Ask it to identify uncertainty instead of filling gaps with guesses. For research, request sources and compare them. For coding, request tests and edge-case review. For files, name the exact pages, fields, or questions. For writing, give the audience and tone. For planning, provide dates, resources, and hard constraints.`],
    ["What to verify before relying on an answer",`Verification should match the risk. Casual brainstorming may need only a quick sanity check. A legal, medical, financial, security, production-code, account, or public-facing decision deserves stronger verification. Check primary sources where available, inspect the actual file or diff, confirm the account state, and make sure an action really completed rather than assuming it did because Cookie described it. If Cookie cannot access a source or system, it should not be treated as having verified that information.`],
    ["Next steps",`Read the specific article that matches your immediate task, then return here when you need the broader context. The article list is intentionally concise so you can jump directly to a procedure, while this overview gives you the surrounding reasoning: what the feature is for, what it depends on, what can go wrong, and what should be checked afterward. If your question crosses topics—for example account security plus privacy, or Code Studio plus deployment—read both areas rather than assuming one page covers the entire workflow.`]
  ];

  return <div className="help-topic-overview">
    <div className="help-topic-banner"><div className="help-topic-icon">{topic.icon}</div><div><span>TOPIC GUIDE</span><h2>{topic.title}</h2><p>{topic.description}</p></div></div>
    <div className="help-topic-meta"><span>{topic.articles.length} focused articles</span><span>Deep guide</span><span>Practical context</span></div>
    <div className="help-topic-sections">{blocks.map(([title,text])=><section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div>
    <section className="help-topic-articles"><div><span>CONTINUE READING</span><h3>Articles in {topic.title}</h3></div><div className="help-article-cards">{topic.articles.map(a=><button key={a.id} onClick={()=>onArticle(a)}><div><b>{a.title}</b><p>{a.summary}</p></div><ChevronRight size={16}/></button>)}</div></section>
  </div>;
}

export default function HelpCenterPage({onClose,onLegal}:{onClose:()=>void;onLegal:(kind:"terms"|"privacy")=>void}){
 const [query,setQuery]=useState("");const [topicId,setTopicId]=useState("start");const [articleId,setArticleId]=useState<string|null>(null);
 useEffect(()=>{const fn=(e:Event)=>onLegal((e as CustomEvent<"terms"|"privacy">).detail);window.addEventListener("cookie:open-legal",fn);return()=>window.removeEventListener("cookie:open-legal",fn)},[onLegal]);
 const topic=topics.find(t=>t.id===topicId)||topics[0];const article=articleId?topic.articles.find(a=>a.id===articleId)||null:null;
 const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return [];return topics.flatMap(t=>t.articles.filter(a=>(t.title+" "+t.description+" "+a.title+" "+a.summary).toLowerCase().includes(q)).map(a=>({topic:t,article:a}))).slice(0,12)},[query]);
 const openTopic=(t:Topic)=>{setTopicId(t.id);setArticleId(null);setQuery("")};
 const openArticle=(t:Topic,a:Article)=>{setTopicId(t.id);setArticleId(a.id);setQuery("")};
 return <div className="help-center">
  <header className="help-head"><div className="help-brand"><div className="help-logo"><BookOpen size={18}/></div><div><b>Cookie Help Center</b><span>Product guides · troubleshooting · privacy · account help</span></div></div><button className="help-close" onClick={onClose} aria-label="Close help"><X size={18}/></button></header>
  <div className="help-hero"><div className="help-hero-copy"><span>COOKIE SUPPORT LIBRARY</span><h1>Help that explains the whole workflow.</h1><p>Choose a topic to get a deep guide, then open focused articles for the exact procedure. Every topic is written around how Cookie actually works rather than a generic feature list.</p></div><label className="help-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search guides, settings, account, files, Code Studio…" autoFocus/></label>
   {query&&<div className="help-search-results">{results.length?results.map(({topic:t,article:a})=><button key={t.id+a.id} onClick={()=>openArticle(t,a)}><span>{t.title}</span><b>{a.title}</b><small>{a.summary}</small><ChevronRight size={15}/></button>):<div className="help-no-results">No articles found. Try a broader term such as “account”, “files”, “memory”, or “security”.</div>}</div>}
  </div>
  <div className="help-body">
   <section className="help-topic-selector"><div className="help-section-heading"><div><span>EXPLORE BY TOPIC</span><h2>{topic.title} and more</h2><p>Select a topic. The selected area opens as a full contextual guide, not just a list of links.</p></div><span className="help-topic-count">{topics.length} topics</span></div>
    <div className="help-topic-grid">{topics.map(t=><button key={t.id} className={topic.id===t.id&&!article?"selected":""} onClick={()=>openTopic(t)}><div className="help-topic-card-icon">{t.icon}</div><div className="help-topic-card-copy"><b>{t.title}</b><p>{t.description}</p><small>{t.articles.length} {t.articles.length===1?"article":"articles"}</small></div><ChevronRight size={16}/></button>)}</div>
   </section>
   <main className="help-article">
    {article?<><div className="help-breadcrumb"><button onClick={()=>setArticleId(null)}>{topic.title}</button><ChevronRight size={13}/><span>{article.title}</span></div><div className="help-article-head"><span>{topic.title}</span><h2>{article.title}</h2><p>{article.summary}</p></div><div className="help-article-body">{article.body}</div><div className="help-article-nav">{topic.articles.map(a=><button key={a.id} className={a.id===article.id?"active":""} onClick={()=>setArticleId(a.id)}>{a.title}</button>)}</div></>:<TopicOverview topic={topic} onArticle={a=>setArticleId(a.id)}/>}
   </main>
  </div>
  <footer className="help-foot"><span>Cookie Help Center · contextual product documentation</span><nav><button className="legal-inline-link" onClick={()=>onLegal("terms")}>Terms of Service</button><button className="legal-inline-link" onClick={()=>onLegal("privacy")}>Privacy Policy</button></nav></footer>
 </div>;
}
