import React from "react";
import {ArrowLeft,LockKeyhole,ShieldCheck} from "lucide-react";

export default function LegalPage({kind,onBack}:{kind:"terms"|"privacy";onBack:()=>void}){
 const privacy=kind==="privacy";
 return <div className="legal-page">
  <header className="legal-head"><button onClick={onBack}><ArrowLeft size={17}/>Help Center</button><div><b>Cookie</b><span>{privacy?"Privacy Policy":"Terms of Service"}</span></div></header>
  <article className="legal-document"><div className="legal-kicker">{privacy?<LockKeyhole size={16}/>:<ShieldCheck size={16}/>} COOKIE</div><h1>{privacy?"Privacy Policy":"Terms of Service"}</h1><p className="legal-updated">Effective October 6, 2026</p>{privacy?<PrivacyBody/>:<TermsBody/>}</article>
 </div>;
}

function TermsBody(){return <div className="legal-copy">
<h2>1. About Cookie</h2><p>These Terms of Service govern your use of Cookie and its websites, applications, AI features, and related services. By creating an account, accessing Cookie, or using the service, you agree to these Terms.</p>
<h2>2. Eligibility and accounts</h2><p>You must be legally permitted to use the service where you live. You are responsible for the information on your account and for keeping your login credentials secure. Do not share your password, verification codes, or reset links.</p><p>You must not create an account for someone else without authorization, impersonate another person, or use another user's account without permission.</p>
<h2>3. Your content</h2><p>You may provide prompts, messages, files, images, code, and other material to Cookie (“Input”). You retain your rights in your Input. You are responsible for making sure you have the rights and permissions needed to submit or share it.</p><p>Cookie may process your Input and produce responses (“Output”) to provide the features you request. You are responsible for reviewing Output before using or sharing it.</p>
<h2>4. AI output and accuracy</h2><p>Cookie uses artificial intelligence. Output may be incorrect, incomplete, outdated, biased, or inappropriate for your situation. Output may also be similar to output generated for other users.</p><p>Do not treat Cookie as the sole source of truth. Check important information against reliable sources and use appropriate human or professional review for medical, legal, financial, employment, education, safety, or other high-impact decisions.</p>
<h2>5. Acceptable use</h2><p>You may use Cookie only in compliance with applicable law and these Terms. You must not use Cookie to harm people, commit fraud, threaten or harass others, facilitate illegal activity, distribute malware, steal credentials, invade privacy, or create or operate unauthorized access to systems.</p><p>You must not bypass rate limits, safety controls, account restrictions, or other security measures. You must not probe, disrupt, overload, reverse engineer, or interfere with Cookie or its infrastructure except where applicable law expressly permits it.</p>
<h2>6. Sharing and public content</h2><p>When Cookie provides a sharing feature, you control whether you create a share link. Anyone who can access a shared link may be able to view the content included in it. Do not share private, confidential, or sensitive information unless you are comfortable with that disclosure.</p>
<h2>7. Plans, limits, and credits</h2><p>Cookie may offer different plans, usage limits, model access, credits, or other account features. Your available features and limits are shown in Cookie and may differ by plan.</p><p>Where payment is required, the price and applicable purchase, renewal, cancellation, and refund terms presented at checkout apply. Credits and promotional benefits may have their own conditions or expiration dates.</p>
<h2>8. Service availability and changes</h2><p>Cookie is continually developed. We may add, remove, replace, or change models, features, limits, interfaces, and integrations. We may also temporarily limit availability for maintenance, security, capacity, or other operational reasons.</p>
<h2>9. Account restrictions</h2><p>Cookie may warn, suspend, restrict, or terminate an account when reasonably necessary to enforce these Terms, protect users, prevent abuse or fraud, respond to security incidents, or comply with law. Temporary restrictions may include an end time.</p><p>Do not attempt to evade a restriction by creating or using another account. If you believe an enforcement action is incorrect, use the support or appeal process made available by Cookie.</p>
<h2>10. Intellectual property</h2><p>Cookie, its software, interfaces, branding, and underlying technology are protected by applicable intellectual property laws. Except as permitted by these Terms or applicable law, you may not copy, sell, redistribute, or modify the service itself.</p><p>Cookie does not grant you ownership of another user's content or Output simply because you can access it.</p>
<h2>11. Security and responsible use</h2><p>Keep your account secure and report suspected unauthorized access. Do not upload secrets, passwords, private keys, or information you are not authorized to disclose. When using Cookie for code or production work, review changes and test them before deployment.</p>
<h2>12. Disclaimers</h2><p>To the extent permitted by law, Cookie is provided on an “as available” and “as is” basis. We do not promise that the service will always be uninterrupted, secure, error-free, or that every Output will be accurate or suitable for a particular purpose.</p>
<h2>13. Limitation of liability</h2><p>To the maximum extent permitted by applicable law, Cookie and its operators will not be liable for indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the service. Nothing in these Terms excludes liability that cannot lawfully be excluded.</p>
<h2>14. Changes to these Terms</h2><p>We may update these Terms when Cookie changes or when legal requirements change. The current version will be made available through Cookie. Where applicable law requires notice of a material change, we will provide it in an appropriate way.</p>
<h2>15. Contact</h2><p>For questions about these Terms, account access, or legal matters, use the support contact or support channel provided by Cookie. This document is general service information and is not legal advice.</p>
</div>}

function PrivacyBody(){return <div className="legal-copy">
<h2>1. About this Privacy Policy</h2><p>This Privacy Policy explains what personal information Cookie may process, why it is used, how it may be shared, and the choices available to you. It applies to Cookie accounts, websites, applications, and services that link to this Policy.</p>
<h2>2. Information you provide</h2><p>Depending on how you use Cookie, we may process information such as your name, username, email address, account credentials, profile details, messages, prompts, files, images, generated content, settings, and other information you choose to provide.</p>
<h2>3. Information collected automatically</h2><p>Cookie may process technical and usage information needed to operate and secure the service. This can include device and browser information, IP address, approximate location derived from network information, timestamps, pages or features used, performance information, and security events.</p>
<h2>4. How we use information</h2><p>We use information to create and authenticate accounts, provide AI responses and other requested features, save conversations and settings, process files, operate Memory where enabled, maintain reliability, provide support, detect abuse, protect security, enforce our Terms, and comply with legal obligations.</p>
<h2>5. AI and service providers</h2><p>Content you send to Cookie may be processed by AI models and infrastructure providers needed to provide the requested feature. We may use service providers for hosting, databases, email delivery, security, analytics, storage, and other operational functions. They receive information only as needed for their role and subject to applicable requirements.</p>
<h2>6. Memory and saved information</h2><p>When Memory is enabled, Cookie may retain selected information from your interactions so future responses can be more useful. You can review or remove available saved memories through Cookie's Memory controls. Removing a memory does not necessarily delete the conversation or other records containing the same information.</p>
<h2>7. Chats, files, and sharing</h2><p>Conversation content and uploaded files may be stored or processed to provide the features you use. If you create a shared conversation or otherwise publish content, information included in that content may be accessible to people who receive the link or otherwise have access to it.</p><p>Temporary chats are designed not to remain in normal chat history, but temporary mode should not be understood as a promise that every technical, security, fraud-prevention, or legal record is immediately deleted.</p>
<h2>8. Security and moderation</h2><p>We may process account, device, usage, and content information to prevent fraud, investigate abuse, protect Cookie and its users, enforce account restrictions, and maintain security. Moderation records may be retained separately from normal chat history when necessary.</p>
<h2>9. Legal reasons and disclosures</h2><p>We may disclose information when required by law, legal process, or a valid governmental request, or when reasonably necessary to protect users, Cookie, our rights, or the public. We may also share information as part of a business transfer such as a merger, acquisition, financing, or sale of assets, subject to applicable law.</p>
<h2>10. Data retention</h2><p>We keep information for as long as reasonably necessary for the purposes described in this Policy, including providing the service, maintaining security, resolving disputes, enforcing our Terms, and meeting legal or operational requirements. Different types of information may have different retention periods.</p>
<h2>11. Your privacy choices</h2><p>Depending on the feature and laws that apply to you, you may be able to access, correct, delete, or otherwise control certain information through Cookie settings or by contacting support. You may also be able to manage Memory, chat history, sharing, notifications, and other account controls from within Cookie.</p>
<h2>12. International processing</h2><p>Cookie and its service providers may process information in countries other than the country where you live. Where applicable, we use appropriate safeguards for international transfers as required by law.</p>
<h2>13. Children</h2><p>Cookie is not intended for people who are not legally permitted to use the service under the laws that apply to them. We do not knowingly request personal information from children who are not eligible to use Cookie. If you believe an ineligible child has provided information, contact support.</p>
<h2>14. Changes to this Policy</h2><p>We may update this Privacy Policy when our services, data practices, or legal requirements change. The current version will be available through Cookie, with the effective date shown at the top.</p>
<h2>15. Contact</h2><p>For privacy questions or requests concerning your personal information, use the privacy or support contact provided by Cookie. We may need to verify your identity before completing certain requests.</p>
</div>}
